In [6]:
import numpy as np

from numpy import array

In [8]:
from numpy import array, float32, int64 

episode_dict = {'action': [array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0])],
                'observation.state': [array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32),
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32)], 
                'timestamp': array([0.0, 0.03333334, 0.06666667, 0.1, 0.13333334], dtype=float32), 
                'frame_index': array([0, 1, 2, 3, 4], dtype=int64), 
                
                'episode_index': array([0, 0, 0, 0, 0]), 
                'index': array([0, 1, 2, 3, 4]), 
                'task_index': array([0, 0, 0, 0, 0])}

In [9]:
import datasets

In [ ]:
datasets.Dataset.from_dict(episode_dict, )

In [1]:
import pandas as pd

df = pd.read_parquet('C:/Users/DHoll/.cache/huggingface/lerobot/danielholl/test1/data/chunk-000/episode_000000.parquet', engine='pyarrow')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   action             48 non-null     object
 1   observation.state  48 non-null     object
 2   timestamp          48 non-null     float32
 3   frame_index        48 non-null     int64
 4   episode_index      48 non-null     int64
 5   index              48 non-null     int64
 6   task_index         48 non-null     int64
dtypes: float32(1), int64(4), object(2)
memory usage: 2.6+ KB
None

In [2]:
df.head(20)

,action,observation.state,timestamp,frame_index,episode_index,index,task_index
0,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.000000,0,0,0,0
1,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.033333,1,0,1,0
2,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.066667,2,0,2,0
3,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.100000,3,0,3,0
4,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.133333,4,0,4,0
5,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.166667,5,0,5,0
6,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.200000,6,0,6,0
7,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.233333,7,0,7,0
8,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.266667,8,0,8,0
9,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.300000,9,0,9,0
10,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.333333,10,0,10,0
11,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.366667,11,0,11,0
12,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.400000,12,0,12,0
13,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.433333,13,0,13,0
14,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.466667,14,0,14,0
15,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.500000,15,0,15,0
16,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.533333,16,0,16,0
17,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.566667,17,0,17,0
18,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.600000,18,0,18,0
19,"[0.0, 195.0, 185.0, 65.0, 0.0, 0.0]","[0.3515625, 187.64648, 176.83594, 66.09375, 0....",0.633333,19,0,19,0

In [15]:
df = pd.read_parquet('C:/Users/DHoll/Downloads/train-00000-of-00018.parquet', engine='pyarrow')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3750 entries, 0 to 3749
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   observation.state   3750 non-null   object
 1   observation.effort  3750 non-null   object
 2   action              3750 non-null   object
 3   episode_index       3750 non-null   int64
 4   frame_index         3750 non-null   int64
 5   timestamp           3750 non-null   float32
 6   next.done           3750 non-null   bool
 7   index               3750 non-null   int64
 8   task_index          3750 non-null   int64
dtypes: bool(1), float32(1), int64(4), object(3)
memory usage: 223.5+ KB
None

In [21]:
df.loc[0, 'action']

array([ 0.01380583, -0.95567006,  1.1642915 ,  0.00153398, -0.2945243 ,
       -0.01073787, -0.06563142,  0.02607767, -0.9541361 ,  1.1612235 ,
        0.00460194, -0.29299033,  0.01073787,  0.01377473], dtype=float32)

In [22]:
df.loc[0, 'observation.state']

array([ 0.0000000e+00, -9.6487397e-01,  1.1673595e+00,  1.5339808e-03,
       -2.9299033e-01, -1.5339808e-03,  7.0105249e-04, -1.5339808e-03,
       -9.6487397e-01,  1.1704273e+00,  1.5339808e-03, -2.8992239e-01,
        1.5339808e-03,  2.9024412e-04], dtype=float32)

In [23]:
type(df.loc[0, 'observation.state'])

numpy.ndarray

In [20]:
from lerobot.common.datasets.lerobot_dataset import *

LeRobotDataset().features

TypeError: LeRobotDataset.__init__() missing 1 required positional argument: 'repo_id'